### PR TITLE
Updated dependencies and integrated isEmojiSelected

### PR DESCRIPTION
**Pull request by noctivityinc**
Updated the dependencies for `react-native-gestures` and `react-native-reanimited` and merged in @EugeneKey's changed.  Cannot install without updating these dependencies

### CODE REVIEW

**Comment by aDamNNNN** [comment]
@het-a-simform @parth-simform @ravir-simform @virajpsimformsolutions @kuldip-simform can someone please review the pull request so it can be merged? It would be very good if it could work with reanimated version 3

**Review by aDamNNNN — APPROVED** [review]
.

**Comment by mukesh-simform** [comment]
@aDamNNNN Currently, we're testing this with the latest reanimated version and validating removal of that emojiAnimatedScaled, after thorough testing we will incorporate these changes and are also aiming for a release soon. Thank you for your contribution and patience @noctivityinc.

**Comment by mukesh-simform** [comment]
Removal of `emojiAnimatedScaled` will impact animation in the reaction popup and also `emojiSelectedContainerStyle` prop has not been passed from the parent component. We will plan reanimated version update to v3 in a separate pull request so closing this. Feel free to raise an issue if needed. Thanks!

**Pull request closed without merging**
